### ISSUE TITLE
How to enter Blockchain.Info Wallet Identifier?

### ISSUE THREAD

**Issue by lincolnquick** [dan-v/bruteforce-bitcoin-brainwallet#15]
Forgive the noobishness, but where do you enter your blockchain wallet identifier? Also, is there an offline version to brute force the wallet.aes.json file?

**Comment by dan-v** [comment]
@lincolnquick - not entirely sure what you mean by where do you enter your blockchain wallet identifier. The purpose of this script is to take a dictionary word, transform it into a the corresponding brainwallet address, and check to see if there have been any historical transactions in the blockchain for this address. 

As far as an offline option with this script, you can use [Abe](https://github.com/bitcoin-abe/bitcoin-abe) to index every transaction since the beginning of time so that you can more quickly iterate through a dictionary of words.
